name: Build Image

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependency
      run: sudo ./.setup-ci-dependency
    - name: Make aur packages
      run: ./build.sh
    - name: Building the image
      run: sudo mkosi
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: output/root.squashfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
